src/pyatmo/auth.py
src/pyatmo/camera.py
src/pyatmo/public_data.py
src/pyatmo/thermostat.py
src/pyatmo/weather_station.py
tests/conftest.py
tests/test_async.py
tests/test_pyatmo.py
tests/test_pyatmo_publicdata.py
tests/test_pyatmo_thermostat.py
tests/test_pyatmo_weatherstation.py

When a camera is not reachable by pyatmo it throws an `aiohttp.client_exceptions.ContentTypeError` exception. This handles it more graceful.

Catch camera ping error

---

src/pyatmo/camera.py
src/pyatmo/helpers.py
src/pyatmo/thermostat.py
src/pyatmo/weather_station.py

Extract raw data processing

---

CHANGELOG.md
setup.cfg
src/pyatmo/auth.py
src/pyatmo/camera.py
src/pyatmo/helpers.py
src/pyatmo/public_data.py
src/pyatmo/thermostat.py
src/pyatmo/weather_station.py

Add type information for distribution along with a few type annotation fixes.

Add type information for distribution

---

CHANGELOG.md
src/pyatmo/auth.py
src/pyatmo/camera.py
src/pyatmo/thermostat.py
tests/test_async.py
tests/test_pyatmo_camera.py
tests/test_pyatmo_thermostat.py

This is a fix for https://community.home-assistant.io/t/netatmo-outdoor-cameras-not-showing-image/341439

[Bugfix] Use get instead of post for retriving images

---

.pre-commit-config.yaml
fixtures/home_status_error_disconnected.json
src/pyatmo/thermostat.py
tests/test_pyatmo_thermostat.py

* Moves pylint under pre-commit to local env due to issues when scanning tests.
* Fix wrong test data

Misc clean up

---

.vscode/tasks.json
src/pyatmo/__init__.py
src/pyatmo/climate.py
src/pyatmo/helpers.py
tests/conftest.py
tests/test_async.py
tests/test_pyatmo_climate.py

Introduce new climate module to eventually replace the thermostat module. This introduces dataclasses for homes, rooms, schedules and modules. The idea is to evolve this into a generic model and roll it out to all other modules and provide a more coherent API.

Introduce climate module

---

CHANGELOG.md
src/pyatmo/helpers.py

Related bug: https://github.com/home-assistant/core/issues/59224

Catch when no body is contained in the response

---

CHANGELOG.md
src/pyatmo/climate.py

Fixes https://github.com/home-assistant/core/issues/62836

Use ID if schedule name is missing

---

CHANGELOG.md
fixtures/homestatus_91763b24c43d3e344f424e8c.json
src/pyatmo/climate.py
tests/test_pyatmo_climate.py

Signed-off-by: cgtobi <cgtobi@gmail.com>

Fix bug when home does not contain valid devices

---

.pre-commit-config.yaml
src/pyatmo/auth.py
tests/test_pyatmo_camera.py

Signed-off-by: cgtobi <cgtobi@gmail.com>

Re-blacken code

---

CHANGELOG.md

Signed-off-by: cgtobi <cgtobi@gmail.com>

Update changelog for v6.2.3

---

CHANGELOG.md
src/pyatmo/home_coach.py
src/pyatmo/weather_station.py

Feature request: https://github.com/home-assistant/home-assistant.io/issues/19159
Signed-off-by: cgtobi <cgtobi@gmail.com>

Fetch favorite weather stations

---

.devcontainer/Dockerfile.dev
CHANGELOG.md
src/pyatmo/modules/__init__.py
src/pyatmo/modules/legrand.py

required to fix https://github.com/home-assistant/core/issues/79438

Add legrand NLPT

---

CHANGELOG.md
fixtures/getstationsdata.json
src/pyatmo/account.py
src/pyatmo/const.py
src/pyatmo/helpers.py
src/pyatmo/home.py

fixes https://github.com/home-assistant/core/issues/79829

Fix weather station issue when homes are empty

---

CHANGELOG.md
src/pyatmo/modules/__init__.py
src/pyatmo/modules/device_types.py
src/pyatmo/modules/legrand.py

fixes https://github.com/home-assistant/core/issues/80923

Add NLUI device class

---

CHANGELOG.md
src/pyatmo/auth.py
src/pyatmo/camera.py

Should fix https://github.com/home-assistant/core/issues/67560
@cgtobi 
Thank you for our session yesterday. I did anyway try to reproduce it locally and therefore probably came up with the correct solution. If I missed something or if you want to add tests, feel free to do so, because I totally skipped this one 😉

Handle camera requests more decent and communicate

---

CHANGELOG.md
src/pyatmo/modules/__init__.py
src/pyatmo/modules/device_types.py
src/pyatmo/modules/somfy.py

Could you accept this PR for adding Somfy shutters support:
JSON data from homesdata Netatmo API:
```
{
"id": "7bac63ca-cde8-489c-8d1b-*******",
"type": "TPSRS",
"name": "Volet Velux",
"setup_date": ******,
"room_id": "******",
"bridge": "somfy://0808-****-****",
"target_position:in_scenario": true
}
```

Adding Somfy shutters

---

src/pyatmo/const.py

Added scopes "read_mhs1" and "write_mhs1" for the management of Bticino MyHome Server 1 modules

Add Bticino MyHome Server 1 scopes

---

.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-test-pypi.yml
.github/workflows/pythonpackage.yml
.pre-commit-config.yaml
README.md
pyproject.toml
setup.cfg
src/pyatmo/camera.py
src/pyatmo/const.py
src/pyatmo/modules/base_class.py
src/pyatmo/modules/module.py
tox.ini

Drop support for python 3.8 to use modern language features

Drop support for python 3.8

---

src/pyatmo/modules/device_types.py

related to https://github.com/home-assistant/core/issues/100988

Add NLPD - Drivia dry contact

---

CHANGELOG.md
src/pyatmo/modules/bticino.py
src/pyatmo/modules/device_types.py

resolves: https://github.com/home-assistant/core/issues/106392

Add shutter capabilities to BNAB, BNAS and BNMS

---

src/pyatmo/modules/base_class.py
src/pyatmo/modules/module.py

Expose the target_position:step property present for shutter devices

shutter: expose target_position:step property
